# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8125be9c6812ea447e11aeda5cd9214d781c25c45c494b0fbd6dcacda6dc737fcb0e88a3f178972c51745831b300a9e853f2d71dc8d5737abc4b75f2d0a3015

test:
  secret_key_base: 179680dd52f50b510d409c6efd3e691aa946c25151420ab93a96bd988a0a40fba10636ef7d49b2b9b357c5204147515a1a745e0d65f54aee288bbed95ba6fb34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
